#!/usr/bin/env bash
#
# Rebase the docx4j fork onto a new upstream xsdata tag.
#
#   tools/rebase-upstream.sh v26.3
#   tools/rebase-upstream.sh v26.3 --no-rebase          # build the base branch only
#   tools/rebase-upstream.sh v26.2 --branch scratch --no-rebase   # self-test
#
# The idea: the rename is never rebased, it is regenerated.  We build a branch
#
#     upstream-renamed-$TAG = $TAG + fork tooling + tools/rename.py output
#
# and then replay only our own feature commits (everything on `docx4j` after the
# current rename commit) onto it.  See docs/fork/REBASING.md.
#
set -euo pipefail

RENAME_SUBJECT='Rename to docx4j_xsdata (generated by tools/rename.py)'
TOOLING_SUBJECT='Fork tooling: rename script, rebase script, fork docs'
FORK_BRANCH=docx4j

usage() {
    sed -n '2,16p' "$0" | sed 's/^# \{0,1\}//'
    exit "${1:-1}"
}

TAG=""
BRANCH=""
DO_REBASE=1
while [ $# -gt 0 ]; do
    case "$1" in
        -h|--help) usage 0 ;;
        -n|--no-rebase) DO_REBASE=0; shift ;;
        --branch) BRANCH="$2"; shift 2 ;;
        -*) echo "unknown option: $1" >&2; usage ;;
        *) TAG="$1"; shift ;;
    esac
done
[ -n "$TAG" ] || usage

cd "$(git rev-parse --show-toplevel)"
BRANCH="${BRANCH:-upstream-renamed-$TAG}"

if [ -n "$(git status --porcelain)" ]; then
    echo "error: working tree is dirty; commit or stash first" >&2
    exit 1
fi

START_BRANCH="$(git rev-parse --abbrev-ref HEAD)"

# ---------------------------------------------------------------------------
# 1. fetch upstream and make sure the tag is there
# ---------------------------------------------------------------------------
echo "==> fetching upstream"
git fetch upstream --tags

if ! git rev-parse -q --verify "refs/tags/$TAG^{commit}" >/dev/null; then
    echo "error: tag $TAG not found on upstream" >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# 2. find the rename commit currently on the fork branch: that is the base the
#    feature commits are replayed off.
# ---------------------------------------------------------------------------
OLD_BASE="$(git rev-list -n1 --grep="^${RENAME_SUBJECT}\$" "$FORK_BRANCH")"
if [ -z "$OLD_BASE" ]; then
    echo "error: no commit titled '$RENAME_SUBJECT' on $FORK_BRANCH" >&2
    exit 1
fi
echo "==> current rename commit on $FORK_BRANCH: $OLD_BASE"
echo "==> feature commits that will be replayed:"
git log --oneline --reverse "$OLD_BASE..$FORK_BRANCH" | sed 's/^/      /'

# ---------------------------------------------------------------------------
# 3. build upstream-renamed-$TAG = $TAG + tooling commit + rename commit
# ---------------------------------------------------------------------------
if git rev-parse -q --verify "refs/heads/$BRANCH" >/dev/null; then
    echo "error: branch $BRANCH already exists; delete it or pass --branch" >&2
    exit 1
fi

echo "==> creating $BRANCH from $TAG"
git checkout -q -b "$BRANCH" "refs/tags/$TAG"

# The tooling has to be in the base branch, otherwise the rebase below (which
# drops everything up to and including the old rename commit) would lose it.
echo "==> copying fork tooling and docs from $FORK_BRANCH"
git checkout "$FORK_BRANCH" -- tools docs/fork
git commit -q -m "$TOOLING_SUBJECT

Copied verbatim from $FORK_BRANCH; the rename below is regenerated from
tools/rename.py rather than rebased."

echo "==> running tools/rename.py"
# stale caches from an editable install would collide with the package move
find . -name __pycache__ -type d -not -path './.venv/*' -prune -exec rm -rf {} + 2>/dev/null || true
python3 tools/rename.py .
git add -A
git commit -q -m "$RENAME_SUBJECT

Upstream: $TAG"
echo "==> $BRANCH ready: $(git rev-parse --short HEAD)"

if [ "$DO_REBASE" -eq 0 ]; then
    echo "==> --no-rebase: stopping here"
    git checkout -q "$START_BRANCH"
    exit 0
fi

# ---------------------------------------------------------------------------
# 4. replay our feature commits onto it
# ---------------------------------------------------------------------------
echo "==> git rebase --onto $BRANCH $OLD_BASE $FORK_BRANCH"
git rebase --onto "$BRANCH" "$OLD_BASE" "$FORK_BRANCH"

cat <<EOF

==> done.  $FORK_BRANCH now sits on $TAG.

Next:
  * update the "currently sits on" line in docs/fork/REBASING.md
  * add a section to docs/fork/CHANGES.md
  * run the tests:  pytest --doctest-glob="docs/*.md"
  * when happy:     git branch -D $BRANCH
EOF
